window.OUTLET_PRODUCTS = [
  {id:'sofa-retratil-bege', name:'Sofá Retrátil 3 Lugares Comfort', category:'moveis', subcategory:'Sala', price:1499, oldPrice:1899, image:'assets/products/sofa-bege.jpg', badge:'Mais vendido', stock:4, description:'Sofá retrátil com tecido macio, assentos profundos e estrutura reforçada. Peça de mostruário em excelente estado.'},
  {id:'geladeira-frost-free-inox', name:'Geladeira Frost Free Inox 375L', category:'eletros', subcategory:'Geladeira', price:1999, oldPrice:2499, image:'assets/products/geladeira-inox.jpg', badge:'Outlet', stock:2, description:'Geladeira frost free com acabamento inox, prateleiras reguláveis e amplo espaço interno.'},
  {id:'fogao-5-bocas', name:'Fogão 5 Bocas Mesa de Vidro', category:'eletros', subcategory:'Fogão', price:1399, oldPrice:1699, image:'assets/products/fogao-5-bocas.jpg', badge:'Oferta', stock:5, description:'Fogão de piso com cinco queimadores, mesa de vidro temperado e forno espaçoso.'},
  {id:'cozinha-planejada', name:'Cozinha Compacta Premium', category:'moveis', subcategory:'Cozinha', price:2599, oldPrice:3199, image:'assets/products/cozinha-planejada.jpg', badge:'Novidade', stock:1, description:'Conjunto compacto com armários superiores e inferiores, ideal para apartamentos e cozinhas funcionais.'},
  {id:'sofa-retratil-cinza', name:'Sofá Retrátil 3 Lugares Urban', category:'moveis', subcategory:'Sala', price:1299, oldPrice:1599, image:'assets/products/sofa-cinza.jpg', badge:'Últimas unidades', stock:2, description:'Modelo retrátil e reclinável em tecido cinza, com design versátil e ótimo aproveitamento de espaço.'},
  {id:'rack-tv', name:'Rack com Painel para TV 65”', category:'moveis', subcategory:'Sala', price:749, oldPrice:999, image:'assets/products/rack-tv.jpg', badge:'Preço baixo', stock:7, description:'Rack com painel, nichos e portas, acabamento amadeirado e espaço para TV de até 65 polegadas.'},
  {id:'geladeira-preta', name:'Geladeira Frost Free Black 410L', category:'eletros', subcategory:'Geladeira', price:2399, oldPrice:2899, image:'assets/products/geladeira-preta.jpg', badge:'Destaque', stock:3, description:'Design black moderno, tecnologia frost free e compartimentos organizadores.'},
  {id:'fogao-preto', name:'Fogão 5 Bocas Black Glass', category:'eletros', subcategory:'Fogão', price:1599, oldPrice:1999, image:'assets/products/fogao-preto.jpg', badge:'Oferta', stock:4, description:'Fogão com mesa de vidro preta, acendimento automático e forno com visor amplo.'},
  {id:'lavadora-12kg', name:'Lavadora Automática 12kg', category:'eletros', subcategory:'Lavadora', price:1799, oldPrice:2199, image:'assets/products/lavadora.jpg', badge:'Economize', stock:3, description:'Lavadora automática com ciclos rápidos, dispenser inteligente e capacidade para 12kg.'},
  {id:'forno-embutir', name:'Forno Elétrico de Embutir 50L', category:'eletros', subcategory:'Forno', price:1199, oldPrice:1499, image:'assets/products/forno-embutir.jpg', badge:'Outlet', stock:2, description:'Forno elétrico de embutir com timer, grill e controle preciso de temperatura.'}
];
